<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html><head>

	<title>Caspar von Wrede.</title>
  	
  	
  	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
 	<meta name="keywords" content="Caspar von Wrede, Caspar v. Wrede, Caspar Wrede">

	<style type="text/css"  >

		p {	margin-left: 10px; 
			font-family: verdana; }
		
		.normal {
			font-family: verdana; }

		body {
			margin-left: 10px; margin-top: 50px; font-family: verdana; font-size:95%}
	
		
	
		
		td {
			padding-bottom:5px; 
			padding-top:5px;
			padding-right:5px;
			padding-left:5px;

			}

		td.stats {
			font-size: 70%; text-align:right; }

		td.contact {
			padding-bottom: 0px; 
			padding-top: 1px; 
			font-size: 80%}
		
		td.title {
			padding: 20px; 
			font-size: 200%; 
			background-color:#FFA703; 
			color:white; 
			font-weight:bold;
			}

		td.link { 
			padding: 3px; 
			border-color: grey ; 
			border-width:1px; border-style:solid; 
			width:100px; 
			font-size:small; 
			text-align:center}

		td.link:hover { 
			background-color: #EDE9E8; }
	
		
		table.all {
			width:700px; 
			border-style:solid; 
			border-color: #E7E2D9; 
			border-width: 5px;}
	
		table.structure { 
			border-style:solid; 
			border-color: #FFBC03; 
			background: #F3F3F3;  
			border-width: 1px;
			padding-bottom:0px; 
			padding-top:0px;
			padding-right:0px;
			padding-left:0px;
			font-size:90%}
	
		table.title { }
	
		a:link {color: #BD8605; text-decoration: none}
		a:visited {color: #BD8605; text-decoration: none}
		a:hover {text-decoration: underline}
	
	</style>
</head>



<body>

<table class="all" align="center">
	<tr><td>
	
	<table width="100%" class="title"> <!-- Title -->	
	<tr>
		<td colspan="6" class="title">Caspar's Website. <br>
		
		<span style="font-size: 40%">&nbsp;so there. </span>  
	
		</td>
	</tr>

	
		<TD class="link"><a href="index.html">Home</a></TD>
		<TD class="link"><a href="nothing.html">Photos</a></TD>
		<TD class="link"><a href="nothing.html">CV</a></TD>
		<TD class="link"><a href="links.html">Links</a></TD>
		<TD class="link"><a href="writing.html">Writing</a></TD>
		<TD class="link"><a href="stats.html">Server</a></TD>
	</TR>

	</table>
	</tr></td>
	<tr><td>

	<!--Body of page-->
	<table width="100%" class="structure" style="border-style: none; background: #FFFFFF;" align="center" >